using BabyBearsEngine.Platform.OpenAL;

namespace BabyBearsEngine.Tests.Unit;

/// <summary>
/// Assertions shared across the decoder tests that exercise the bundled sine-wave fixtures. Each
/// fixture is a 1-second 440 Hz sine wave generated by ffmpeg, whose <c>sine</c> filter outputs at
/// amplitude 1/8 — so the decoded 16-bit PCM peaks land around ±3000 rather than ±32767. The
/// assertions below verify the decoded PCM is a real signal with both polarities and a healthy
/// non-zero-sample count — anything that would fail (silence, DC offset, single-polarity output,
/// trimmed-to-stub buffer) is exactly the kind of decoder bug we want these tests to catch.
/// </summary>
internal static class AudioFixtureAssertions
{
    // ffmpeg's sine filter outputs at amplitude 1/8 (~±4096 in 16-bit); after lossy encoding
    // (Vorbis / MP3 / Opus) the decoded peaks land around ±2700–3000. ±2000 is the threshold for
    // a clearly-non-silent sample; comfortably below the expected peak but well above any DC
    // offset or quantisation noise a buggy decoder might produce.
    private const short PeakThreshold = 2000;

    /// <summary>
    /// Asserts that <paramref name="decoded"/> contains samples near a real positive peak and a
    /// real negative peak, and that at least a few thousand samples are non-zero.
    /// </summary>
    public static void AssertSineWavePresent(DecodedAudio decoded)
    {
        bool hasPositivePeak = false;
        bool hasNegativePeak = false;
        int nonZeroSamples = 0;

        for (int i = 0; i < decoded.Pcm.Length; i += 2)
        {
            short sample = (short)(decoded.Pcm[i] | (decoded.Pcm[i + 1] << 8));
            if (sample > PeakThreshold)
            {
                hasPositivePeak = true;
            }
            if (sample < -PeakThreshold)
            {
                hasNegativePeak = true;
            }
            if (sample != 0)
            {
                nonZeroSamples++;
            }
        }

        Assert.IsTrue(hasPositivePeak, $"Expected samples > +{PeakThreshold} (positive peak of the sine wave).");
        Assert.IsTrue(hasNegativePeak, $"Expected samples < -{PeakThreshold} (negative peak of the sine wave).");
        Assert.IsGreaterThan(1000, nonZeroSamples);
    }
}
